version: "3.8"

services:
  localstack:
    container_name: "${LOCALSTACK_DOCKER_NAME-localstack_main}"
    image: localstack/localstack
    ports:
      - "53:53"
      - "53:53/udp"
      - "443:443"
      - "4566:4566"
      - "4571:4571"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    expose:
      - 53
      - 443
      - 4566
      - 4571
    environment:
      - SERVICES=s3,ssm,kms,dynamodb
      - DATA_DIR=/tmp/localstack
      - LS_LOG=trace
  ec2sim:
    depends_on:
      - localstack
    environment:
      S3_URL: http://localstack:4566
    volumes:
      - $PWD/ansible:/ansible
    build:
      context: .
      dockerfile: ec2/Dockerfile
